service: adobe-sign-controller

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev

functions:
  getAgreement:
    handler: lib/handler.getAgreement
    events:
      - http: GET /
