service: adobe-sign-api

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev

functions:
  getAgreement:
    handler: lib/agreements-controller.getAgreement
    events:
      - http: GET /
