service: adobe-sign-api

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    REGION: ${opt:region, 'us-east-1'}
    STAGE: ${opt:stage, 'dev'}
    CACHE_ENDPOINT: { 'Fn::ImportValue': 'AdobeSign-ElasticCacheCluster-Endpoint' }
    ADOBE_SIGN_DB_CONNECTION_LIMIT: 5
    ADOBE_SIGN_DB_HOST: aa98v5e4cexl82.cxkcyw1kssxt.us-west-2.rds.amazonaws.com
    ADOBE_SIGN_DB_USER: root
    ADOBE_SIGN_DB_PASSWORD: password
    ADOBE_SIGN_DB_DATABASE: adobesigndev
    
functions:
  getAgreement:
    role: lambdaRole
    handler: lib/agreements-controller.getAgreement
    vpc:
      securityGroupIds:
        - { 'Fn::ImportValue': 'AdobeSign-ServerlessSecurityGroup-GroupId' }
      subnetIds:
        - { 'Fn::ImportValue': 'AdobeSign-PrivateSubnetA-Ref' }
    events:
      - http:
          path: agreements/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  getTemplate:
    role: lambdaRole
    handler: lib/templates-controller.getTemplate
    vpc:
      securityGroupIds:
        - { 'Fn::ImportValue': 'AdobeSign-ServerlessSecurityGroup-GroupId' }
      subnetIds:
        - { 'Fn::ImportValue': 'AdobeSign-PrivateSubnetA-Ref' }
    events:
      - http:
          path: templates/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  createTemplate:
    role: lambdaRole
    handler: lib/templates-controller.createTemplate
    vpc:
      securityGroupIds:
        - { 'Fn::ImportValue': 'AdobeSign-ServerlessSecurityGroup-GroupId' }
      subnetIds:
        - { 'Fn::ImportValue': 'AdobeSign-PrivateSubnetA-Ref' }
    events:
      - http:
          path: templates/{id}
          method: post

resources:
  Resources:
    lambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: AdobeSignApiLambdaRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:logs"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "log-group:/aws/lambda/*:*:*"
                - Effect: "Allow"
                  Action:
                    - "s3:PutObject"
                  Resource:
                    Fn::Join:
                      - ""
                      - - "arn:aws:s3:::"
                        - "Ref": "ServerlessDeploymentBucket"
                - Effect: "Allow"
                  Resource: "*"
                  Action:
                    - "secretsmanager:GetResourcePolicy"
                    - "secretsmanager:GetSecretValue"
                    - "secretsmanager:DescribeSecret"
                    - "secretsmanager:ListSecretVersionIds"
                    - "secretsmanager:ListSecrets"
                - Effect: "Allow"
                  Resource:
                    - { 'Fn::ImportValue': 'AdobeSign-TemplatesTable-Arn' }
                    - { 'Fn::ImportValue': 'AdobeSign-AgreementsTable-Arn' }
                  Action:
                    - "dynamodb:BatchGetItem"
                    - "dynamodb:GetItem"
                    - "dynamodb:Query"
                    - "dynamodb:Scan"
                    - "dynamodb:BatchWriteItem"
                    - "dynamodb:PutItem"
                    - "dynamodb:UpdateItem"