service: adobe-sign-api

plugins:
  - serverless-bundle

provider:
  name: aws
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'secretsmanager:GetResourcePolicy'
            - 'secretsmanager:GetSecretValue'
            - 'secretsmanager:DescribeSecret'
            - 'secretsmanager:ListSecretVersionIds'
            - 'secretsmanager:ListSecrets'
          Resource:
            - '*' 
  runtime: nodejs12.x
  environment:
    REGION: ${opt:region, 'us-east-1'}
    STAGE: ${opt:stage, 'dev'}

functions:
  getAgreement:
    handler: lib/agreements-controller.getAgreement
    events:
      - http:
          path: agreements/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
