service: adobe-sign-api

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    REGION: ${opt:region, 'us-east-1'}
    STAGE: ${opt:stage, 'dev'}
    CACHE_ENDPOINT: { 'Fn::ImportValue': 'AdobeSign-ElasticCacheCluster-Endpoint' }
    AGREEMENT_WEBHOOK_QUEUE_URL: { 'Fn::ImportValue': 'AdobeSign-AgreementWebhookQueue-Url' }
    WORKDAY_WEBHOOK_QUEUE_URL: { 'Fn::ImportValue': 'AdobeSign-WorkdayWebhookQueue-Url' }
    
functions:
  getAgreement:
    role: lambdaRole
    handler: lib/agreements-controller.getAgreement
    vpc:
      securityGroupIds:
        - { 'Fn::ImportValue': 'AdobeSign-ServerlessSecurityGroup-GroupId' }
      subnetIds:
        - { 'Fn::ImportValue': 'AdobeSign-PrivateSubnetA-Ref' }
    events:
      - http:
          path: agreements/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  createSigningUrlAgreement:
    role: lambdaRole
    handler: lib/agreements-controller.createSigningUrlAgreement
    vpc:
      securityGroupIds:
        - { 'Fn::ImportValue': 'AdobeSign-ServerlessSecurityGroup-GroupId' }
      subnetIds:
        - { 'Fn::ImportValue': 'AdobeSign-PrivateSubnetA-Ref' }
    events:
      - http:
          path: agreements/create/{template_id}
          method: get
          request:
            parameters:
              paths:
                template_id: true
  getTemplate:
    role: lambdaRole
    handler: lib/templates-controller.getTemplate
    vpc:
      securityGroupIds:
        - { 'Fn::ImportValue': 'AdobeSign-ServerlessSecurityGroup-GroupId' }
      subnetIds:
        - { 'Fn::ImportValue': 'AdobeSign-PrivateSubnetA-Ref' }
    events:
      - http:
          path: templates/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  putTemplate:
    role: lambdaRole
    handler: lib/templates-controller.putTemplate
    vpc:
      securityGroupIds:
        - { 'Fn::ImportValue': 'AdobeSign-ServerlessSecurityGroup-GroupId' }
      subnetIds:
        - { 'Fn::ImportValue': 'AdobeSign-PrivateSubnetA-Ref' }
    events:
      - http:
          path: templates
          method: put
  webhookVerification:
    role: lambdaRole
    handler: lib/webhook-controller.webhookVerification
    vpc:
      securityGroupIds:
        - { 'Fn::ImportValue': 'AdobeSign-ServerlessSecurityGroup-GroupId' }
      subnetIds:
        - { 'Fn::ImportValue': 'AdobeSign-PrivateSubnetA-Ref' }
    events:
      - http:
          path: webhook
          method: get
  webhookPost:
    role: lambdaRole
    handler: lib/webhook-controller.webhookPost
    vpc:
      securityGroupIds:
        - { 'Fn::ImportValue': 'AdobeSign-ServerlessSecurityGroup-GroupId' }
      subnetIds:
        - { 'Fn::ImportValue': 'AdobeSign-PrivateSubnetA-Ref' }
    events:
      - http:
          path: webhook
          method: post
  processAgreementWebhook:
    role: lambdaRole
    handler: lib/agreements-controller.processWebhook
    vpc:
      securityGroupIds:
        - { 'Fn::ImportValue': 'AdobeSign-ServerlessSecurityGroup-GroupId' }
      subnetIds:
        - { 'Fn::ImportValue': 'AdobeSign-PrivateSubnetA-Ref' }
    events:
      - sqs:
          arn: { 'Fn::ImportValue': 'AdobeSign-AgreementWebhookQueue-Arn' }
          batchSize: 1

resources:
  Resources:
    lambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: AdobeSignApiLambdaRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:logs"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "log-group:/aws/lambda/*:*:*"
                - Effect: "Allow"
                  Action:
                    - "s3:PutObject"
                  Resource:
                    Fn::Join:
                      - ""
                      - - "arn:aws:s3:::"
                        - "Ref": "ServerlessDeploymentBucket"
                - Effect: "Allow"
                  Resource: "*"
                  Action:
                    - "secretsmanager:GetResourcePolicy"
                    - "secretsmanager:GetSecretValue"
                    - "secretsmanager:DescribeSecret"
                    - "secretsmanager:ListSecretVersionIds"
                    - "secretsmanager:ListSecrets"
                - Effect: "Allow"
                  Resource:
                    - { 'Fn::ImportValue': 'AdobeSign-TemplatesTable-Arn' }
                    - { 'Fn::ImportValue': 'AdobeSign-AgreementsTable-Arn' }
                  Action:
                    - "dynamodb:BatchGetItem"
                    - "dynamodb:GetItem"
                    - "dynamodb:Query"
                    - "dynamodb:Scan"
                    - "dynamodb:BatchWriteItem"
                    - "dynamodb:PutItem"
                    - "dynamodb:UpdateItem"
                - Effect: "Allow"
                  Resource:
                    - { 'Fn::ImportValue': 'AdobeSign-AgreementWebhookQueue-Arn' }
                    - { 'Fn::ImportValue': 'AdobeSign-WorkdayWebhookQueue-Arn' }
                  Action:
                    - "sqs:ReceiveMessage"
                    - "sqs:DeleteMessage"
                    - "sqs:SendMessage"
                    - "sqs:GetQueueAttributes"
                - Effect: "Allow"
                  Resource:
                    - { 'Fn::ImportValue': 'AdobeSign-AdobeSignBucket-Arn' }
                  Action:
                    - "s3:PutObject"