service: adobe-sign-database

provider:
  name: aws

resources:
  Resources:
    TemplatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${opt:stage}-templates
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
  Outputs:
    TemplatesTableARN:
      Description: "ARN of the TemplatesTable"
      Value:
        Fn::GetAtt:
          - TemplatesTable
          - Arn
      Export:
        Name: AdobeSign-TemplatesTable-Arn
        

    