service: adobe-sign-database

provider:
  name: aws

resources:
  Resources:
    TemplatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${opt:stage}-templates
        AttributeDefinitions:
          - AttributeName: adobeSignId
            AttributeType: S
        KeySchema:
          - AttributeName: adobeSignId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    AgreementsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${opt:stage}-agreements
        AttributeDefinitions:
          - AttributeName: adobeSignId
            AttributeType: S
          - AttributeName: asuriteId
            AttributeType: S
          - AttributeName: status
            AttributeType: S
        KeySchema:
          - AttributeName: adobeSignId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: asuriteId-status-index
            KeySchema:
              - AttributeName: asuriteId
                KeyType: HASH
              - AttributeName: status
                KeyType: RANGE
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - adobeSignTemplateId
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
  Outputs:
    TemplatesTableARN:
      Description: "ARN of the TemplatesTable"
      Value:
        Fn::GetAtt:
          - TemplatesTable
          - Arn
      Export:
        Name: AdobeSign-TemplatesTable-Arn
    AgreementsTableARN:
      Description: "ARN of the AgreementsTable"
      Value:
        Fn::GetAtt:
          - AgreementsTable
          - Arn
      Export:
        Name: AdobeSign-AgreementsTable-Arn
        

    