service: serverless-lerna-yarn-service1

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev

functions:
  get:
    handler: lib/handler.main
    events:
      - http: GET /

